# This file was generated by GoReleaser. DO NOT EDIT.
cask "cysmiq" do
  name "cysmiq"
  desc "Cysmiq CLI"
  homepage "https://cysmiq.com"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cysmiq"

  on_macos do
    on_intel do
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_darwin_amd64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
      sha256 "fd1bf5a714f685c6527649ad2c966bb20ee262cd2fb42ace4885bd92c356809f"
    end
    on_arm do
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_darwin_arm64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
      sha256 "5151a2599dbb34ce62b8a2149715f8858edb65dc85f1d2ec26fac728fed9d049"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_linux_amd64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
      sha256 "c498fdf8d2ffa59dae13a3366e1f6853e1bf7a8eae8033224952eec14ffc95f6"
    end
    on_arm do
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_linux_arm64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
      sha256 "f1fafd4bd76a3cb4e603e3cbf43e22de1a6a9c17fd972b7834e8270e3695ba3b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cysmiq"]
    end
  end

  # No zap stanza required
end
