# This file was generated by GoReleaser. DO NOT EDIT.
cask "cysmiq" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "a27fce5ec72f4abcbae1e80f102e0b7446e34dfe3d397e22ffd71ef5d31c9c8a"
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_darwin_amd64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
    end
    on_arm do
      sha256 "0de86df652f68653102cd765fd8d734e73b1312c6ae19144010f31bcfda3002b"
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_darwin_arm64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
    end
  end

  on_linux do
    on_intel do
      sha256 "001b3db10dfe2f8bde56ac6ab07a3bdaf0653fd63e49d245aaf136f6a5dac18a"
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_linux_amd64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
    end
    on_arm do
      sha256 "a8a7216f7fa29529980636158f9114a812a7777521d8205b5e6c5813fae81146"
      url "https://github.com/cysmiq/cli-releases/releases/download/v#{version}/cysmiq_linux_arm64.tar.gz",
        verified: "github.com/cysmiq/cli-releases"
    end
  end

  name "cysmiq"
  desc "Cysmiq CLI"
  homepage "https://cysmiq.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cysmiq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cysmiq"]
    end
  end

  # No zap stanza required

end
